keys:
  - &sab_nz age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
  - &sab_mbp16 age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
  - &sab_beez age15drpfd2kkm32g23wef9ptzyy8slrzhyk5cstwnn5pdlwtt37cqsskx2l2k
  - &sab_zanoza age1n3q6hj36mkzxntdl7zmws7l7zna8z8f930h2tj00vwc2lucszyxsdd4pzl
  - &host_mbp16 age17tnup59gy7jvj65la8nud0y6ukf57w0mueh3e4hxx5npwsa5x44sv765ru
  - &host_nz age1ranl5gsq43t0z22s28zdhvfzrvqqpmwqcjc3h6latfa4rrruxpps34vgqj
  - &host_beez age1e4jdrpwxc35qwn4y82t0824m2whqq9pgkev6h8crp2ywee540gvst332lj
  - &host_zanoza age1xz35v23vpnudp2u7el44cv32fdzc0sc42x0yzs2kl58dcfdpdy3qt9j4y2
creation_rules:
  - path_regex: secrets/sab/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab_nz
          - *sab_mbp16
          - *sab_beez

  - path_regex: secrets/nz@sab/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab_nz
          - *sab_mbp16
  - path_regex: secrets/mbp16@sab/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab_nz
          - *sab_mbp16
  - path_regex: secrets/mbp16/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab_mbp16
          - *host_mbp16
  - path_regex: secrets/nz/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab_nz
          - *host_nz
  - path_regex: secrets/beez/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sab_beez
          - *host_beez
  - path_regex: secrets/zanoza/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *host_zanoza
          - *sab_nz
          - *sab_mbp16
          - *sab_zanoza
