example_key: ENC[AES256_GCM,data:FoIx/kdpuqhEJJNojGE=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:MG4Im9DSMgeLDK3xtfNKiQ==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:M4tyX/WeQfhUnRIppRiWom7G+YJBi38Puf8YGbgLNmhfbNjc1Rg2hnzs1yr+wYCF8zyioA5zpvMn2/dV3XpESc9qS+N/Xxk7gAmpEhCJBrIRPwXSX/ZTsGTAYn4/VOHxBpkj6299UCzIG43hGsE3deHuJ8lNCsmbFwZfv+3Z3vTgHHSUZDqQIWpnhapAzMvDb1Mjcm0=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:Cn03LqhC4cMvdTONAIGibg==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:rF++aMCS1M050mG4vvCB8q2M90IMwSanzwwA4EL0Zm+0wG7zkyrkUQVaxXOHM7DUNCGAGqPdavdIyRlp9fS18D2ZAlUqAecZlwMLuHv2Bsive4Bk2ruZjvUjOQHGgY6v73mi657L5FtEc2sWJSpUSN6srYS2Wpc5Hh8IWWqiUgZK3FcBFCLIhCN8GbDKh4LyId7xpFH1guD5F8dUyXgwxwLk9bxgm+IJY8ZhJdpn+IMfPY68SsIj2yo/oukTfDWwaHCMorni/Vhm+8X42G/ny6zCg90E+pV5c18MP6Zu4RwFPfVzAFpZQmQimpYZRDkxwx2h/xhFv2tFFYI0fPhU3kJ3LoVeQfsfibITTwOOtyRgNJ/TuMfyfOrOUKvmGRq59RBEBFJ8YDwPsMagBZMZve0E9itLDpFaQu6lSXB/2WleLLTFx0JyBtcN8t+XhzccQKpi3XdcFGFSGJUkjoX5/UNSClRTmHzdPe1lUIm9HGH/hKln4Ezc3ofZ2THr3dki0LiYzxm5a7yetEruVLQc2+BE9JGXblCzThE=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:FkGIP3lZek8N+V6s46D7ZA==,type:str]
atuin_key: ENC[AES256_GCM,data:DNacPHovEkDYmBdf0bDmLNTH2abdf+epy2vdp8cL+/Y09K+O5u1ZyB7dcoUmR81dvwBEHiWDcagHg0H2zziKtQ==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:tbrrIk+1YWN9MZEuxj52nQ==,type:str]
env_credentials: ENC[AES256_GCM,data:N/rWvFpmptfw8z6TicJFz8kCwRPOjrz7fomPT8J+OpIjcavmZXYFvgjSrWlTIEMcdCv31ubsi3QkQN07f2mH2iYoXEsBqg2mLZFEPZAVM3BMsHqWIqWd43GExsNwMJ8rw+SsaPSrPW76qgINR81xmcHVj6nvmbLMywRh0eVP/a3QLsWdwaNy62KKNvZhjhGTS3lGwtBPn55+mQ5s+qHFAsLvoZzcN7j7qtvVxtfzMuh6rOIokyiwj36ngqhnux4FKs3aKzZWeAZeGnH4W85f47CzUg/Q6lXs8X94T4D8qVK49hNO6u0vdwR0OTZ1OEZQ2vFpiE3ZbH6aOUl+F0swrJr7YIwvWFmT1F3x+n8/09oEs2g1LE+ivvNmR0zMosNogA8ZIGVlTKy3rgIRbe0NXIN6l1zcN0HOSsrIb1+l0CH3VAMJ4St61h9Cxr8X1leD4r0WKrjzqr1Vmxd2kmUtfVY3/l81aNTZFmAKxnISWbQKtDB1+2Yz/8e1YV8d1tSE0gKJR4iujUva/S2W0hIgWITTn+3qqUQhaUf9y6iRtMsbXTD9jU64nJOWPxkEuif2E8D8fzWbKWSkSl2C3MharoYYz9cLKyd6qP7Ukpzq4NToc3rJD/C79Lv6yHF9rBhVe3HvnCTdJARUE86w5s1v62hU8NtjeVNqqbcWX9YwoXWWcKsXpx1kIfuo/tVBUoz8nvI9c5jwh0npnBxHKKo2wU11MTtxFncQtzl8YhdLZvAunB5JdKJMzz3+XAUeFTGtmNwR0OP6mn3KfzlTQarVDxOiosQ7vg9cIT27dcVL64KZF/kHob42DrRTsn7FVI0Aq95bmhNcKPLdQhRocKpCAoUKCcGEwrUKzOEEcY9+vQ/Y3l/KuZFlXjNyUZBMN5IvzJbXfMe8qQJVLzWfKPYaiheuFvFoG01oFBrijOLdqDQ45IaOkgliQQmjkjLzgzC6BpJP+htzMBU6tTQzKUk5Vmaq,iv:ajDlpHdXgnAnucCGi1cgq3/nvw0gYkgtINZozKm70uM=,tag:Hs7va3yfb/aBcSHvMKac3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZlZYOFcyc2JtKzVmbVZX
            eE02OXZZeDhhWjFZOHpRd3pCTUUrZm5RVFdVCkJ3VTAydGUwUnZ3KzlNTXhFSk11
            bUhGdkpidVFWdFZZb0VxZFJyMHBmSWsKLS0tIDVnR3MrcmxPNy8vcytZVHNLQ1Ns
            RTdFb21PWjJCYitCdUVpZWN6aW15RGsKLR+wUWs7UPTTu5Sm5BChVBgMHXGujx8o
            kqPfesci2xc3+BPINkxnfZ3VyRq0qZe0VKIyJqXAKTrc7bcuI97slA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcW16ZGVDZVBxQXlORklx
            Y0hNNzFTbTg0VDNXTWMzeG9yYVYwTEU5c1ZJCm5leWpnQ2tYS3pIYTdrNVk0d09M
            NTNHV2hPcDI0RUlxOE91QzdZN1J0NE0KLS0tIHBCU1MrTWlFMlhHZTJncWcyVlFa
            emF4dVVibnlXWVpCQlhtRmx3dzNINXcK4zIuu8uCoNJ/OpGUqTMRSYnJpPxojBvp
            RRBbryEAuLmKCzvXZA4p9RgG0dQjjk78nNF1DiY6Pl5mCxZ+Zk24iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ggtc2y8xmwftkdrasxvk4kschd5r7xsjv3kzhvx2k60l6mtan95q0gw0yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNS96dGRrU3lTck02TkxN
            YUtZcTFRRzV5Mmh1VTRvVGZTZGRVRzNndFhNCmlEdVJTcEhKRUI1MER6a0NyRGdQ
            YnEyUEJNTzZlNTBjVGtDRmFtTTA3M00KLS0tIGkvN2h1OW4rSUVWc2ZoVXpGMjhE
            QzQrTHV0ZDI3K1ZXMUNnaVpyZHVXYkkKOr5WLIXYlhAXdx6/44Ti/EtMXy3jK3az
            JMVDAZutnNxRWIkS3VrAb2vWUtYo2eY+W6frzPrx1CLC/cHXYetaWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
    lastmodified: "2026-04-30T07:00:53Z"
    mac: ENC[AES256_GCM,data:945aFgqpmivyIlbCZVm32FwC8iGqDWoNZYIc+SwIwz404X2Q/4WCDUEG+SfItM4KYeO64x3zLEaNG5q/fI1OyQURrmIVJ7kZzG0HUZmLtouUibF+3J0sYVm8YWfB1TUe1zf/883tkaXaWetuEmK+WjrhvIviCmjyR4wrzk5DroM=,iv:AQDxaojQF0U4rqj3NnifUQNr+aZmU6KKj/6MRwOAuko=,tag:TAEtkmOT5mUWdDuzgcMrSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
