example_key: ENC[AES256_GCM,data:FoIx/kdpuqhEJJNojGE=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:MG4Im9DSMgeLDK3xtfNKiQ==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:M4tyX/WeQfhUnRIppRiWom7G+YJBi38Puf8YGbgLNmhfbNjc1Rg2hnzs1yr+wYCF8zyioA5zpvMn2/dV3XpESc9qS+N/Xxk7gAmpEhCJBrIRPwXSX/ZTsGTAYn4/VOHxBpkj6299UCzIG43hGsE3deHuJ8lNCsmbFwZfv+3Z3vTgHHSUZDqQIWpnhapAzMvDb1Mjcm0=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:Cn03LqhC4cMvdTONAIGibg==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:rF++aMCS1M050mG4vvCB8q2M90IMwSanzwwA4EL0Zm+0wG7zkyrkUQVaxXOHM7DUNCGAGqPdavdIyRlp9fS18D2ZAlUqAecZlwMLuHv2Bsive4Bk2ruZjvUjOQHGgY6v73mi657L5FtEc2sWJSpUSN6srYS2Wpc5Hh8IWWqiUgZK3FcBFCLIhCN8GbDKh4LyId7xpFH1guD5F8dUyXgwxwLk9bxgm+IJY8ZhJdpn+IMfPY68SsIj2yo/oukTfDWwaHCMorni/Vhm+8X42G/ny6zCg90E+pV5c18MP6Zu4RwFPfVzAFpZQmQimpYZRDkxwx2h/xhFv2tFFYI0fPhU3kJ3LoVeQfsfibITTwOOtyRgNJ/TuMfyfOrOUKvmGRq59RBEBFJ8YDwPsMagBZMZve0E9itLDpFaQu6lSXB/2WleLLTFx0JyBtcN8t+XhzccQKpi3XdcFGFSGJUkjoX5/UNSClRTmHzdPe1lUIm9HGH/hKln4Ezc3ofZ2THr3dki0LiYzxm5a7yetEruVLQc2+BE9JGXblCzThE=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:FkGIP3lZek8N+V6s46D7ZA==,type:str]
atuin_key: ENC[AES256_GCM,data:DNacPHovEkDYmBdf0bDmLNTH2abdf+epy2vdp8cL+/Y09K+O5u1ZyB7dcoUmR81dvwBEHiWDcagHg0H2zziKtQ==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:tbrrIk+1YWN9MZEuxj52nQ==,type:str]
env_credentials: ENC[AES256_GCM,data:7ujQsy56cO335YryRdJi/B/YyP3XeMepli0FOzm0hnwbOyye9xjKUDO/n1FBe4o83ebk+vcULArJJbos6dquqjEidBOcdDwSNl1kKQj7VlcJvbnCt8OxqZ7LRVFE9femrZx0tkbBfd2ueHrzzcBAZh8vxm3hyPZSPiRDTMdykUsKodBX+C0WAaVRpbay3svLwQ8yCxpkJ3oZag4pjDVEdKDQCOC5cWKIrOMrFOF5hzSpJqtMPIpEq/tgunvQ59sQvU+kh4QQ95HjH6KepFD79k+4Z5+bk6/hgl/sdeLdW55bK8/052LNFOJCUI5v5NbNMy+54ivjKk0bjPSLgYp2ePFPE6tu7zxFL4lPVdmJd84iXwrN9swpQNbtm3hWj6zCR0RhPIdh4J8BBOtOVHK4QFLa24/k/25O9hZPNRCaKGVJil7YwqizfPM/q5O/f3twhvknJ/BPkHNikbwZDLXjfU0iUJHb5JtjHTRjpooIUcdAZRwJWwlPWRmGxUKYUgm3ib0kFFzw8sYjFVrD3AG0BIqu4nVPW/LY/ridFdwFeM55YQ6BBG80smnskCokBL7MFrNs1BY12uS4OvNFCsvePKXpU1Rf+z0xQF9N+CF1XCMSmKez1qlL3VPduuGfTcPSDTv3JSiOIQN8,iv:E5um+hZ2I4FMG9RzSa6rui/nAjDHPT1unz+wxtFqN+o=,tag:7JoS0XsNycWsdsc9qR+CzA==,type:str]
sops:
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeU1mZFE0cXNOUXY5WkVS
            QlJqeUVOSWZYZTJLU0NKQjhKWFpkejVVbFhnCk1lMm41cFI4MUI5T3ZhSURzaFNa
            enNpWS91RjRDSkJoQWNNajByR2NlWEEKLS0tIEJYSCtHR3FUNVp1TC9EbDY2Slhz
            NGtVa0pPYkNIVmk5ekgxZnhaWjY1eGsKG5rRPHE0pujYsP3Uebv/EF3/mMEAmiBo
            C7rSAflz0p+bj0YVSfBaUBrvE59hiyKDNSRckHVI2C1Vn0jeQz8gtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc3FWK2xVUFA3TTBkVUNJ
            b1dFeEduUUw1ekJUUWUwOHBwaVpVU3FkVldvCjlDaUdVd0NicDl1UXhHSjBidGQw
            R1Rwa0FwOFBOQmJUcWNJb3FMTXo2VUkKLS0tIDVacXVYYTdPY2FlRlNoeTc2UTJz
            MnplNEh5bzlVcUV5SWZteENxZ2IxcU0KAsutZ4lEVvbcrRDsx7885vVqnAVQ/MID
            XQd+VtO9BFRT6BWyaEnwu+/SQfoypgtHztRZR35ZHQQWLZ3Ew/ZgXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15drpfd2kkm32g23wef9ptzyy8slrzhyk5cstwnn5pdlwtt37cqsskx2l2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMVhTWmRnSDZ0NFkrS0Zm
            SFkwMi8wTXgzVFpMeStpWHlKVG5WajdKRkFNCkNIUjV2OGlmd1VRNE5MS2NwZHpG
            NlhYSHREUHRmSFBYbW53NkhaMitNZEEKLS0tIFdrRElTcVpPYnQyK1R5UmdkVjBv
            YUZrVFRuNTlYTXB6dGNyak8zSDdMMXMK6mefAGl9dzBnW4kgwoITFyLhjTEyY3Zq
            b3uzueM64YfF90rDvhlH/KHnCoW6APace0yYtg6Dg71qPfQ4yI4C8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mv05td5h3m8wa3cqxm0npepn8jlqhrvsk9pcaewj6lmqzzew59mqwqyats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN0F6dGtacU1TZGNFREMx
            Z2JMZmpuMEMzaVhpcjIzNFJGSFZ6Ui9mZ1hjClBtUDBXSzg4TE0yRnh6d3F6MXR0
            S1RLR3J0a2g0M3ZYRmdNSGRvUFlKdkEKLS0tIGJUdzFYYUlaNGpET04vRTBVM1NY
            dTUzLzZLK3I3cGkzY2N4M2xWMFZFU1kKxbIBu2TDi1dTAeQCb4G3+1NwnuXu59SD
            iRNuM0+ZiliaRYPwptPNLQsWoY1wJASH+3R2U8b0XRJ3XXZZf5IuQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERm4ra3lya2tYLys2QUMr
            Ti9kSlVTczgwOXY4UmkxYkFWWnpRdXQ1LzFBCjAxd1hYc0c1M2c3cmNCZVQvclM1
            MXhRUlRpMHhDZkIyTVFJWTlsb3JhcWsKLS0tIC9VYlN2c1ZHcG42T3ZaSXRidTZC
            bi92OEZDR09yNmRJWUpuNkxZSDhtK2cK4z1iQbc7WcK51lZmVCsLPgipAnu8wRpt
            P1u0/Eninuwyg/CL4WmBOG6qjal6Q7ydpL0qg9xeEhMGot+Oxmyl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T07:35:25Z"
    mac: ENC[AES256_GCM,data:kTkRHlj14JHmrUttdI8pGrqe+Btudvf+MWccuduzC5RTziVB7M9pq9HihjLWfnggzyyMBrwLRxwwudCvgVZ8WYkwxRULNhgXpeGIo3xexi183rk2QFF1exF+MN7O9DvwgbzumD781GpeM9KSHa2/cwE9APdW9Rj5YRLTWFs2f+E=,iv:CvONC0SA8IuZSojvQRDdT6Vls3YQhbYHPPkSrN5sKuk=,tag:URB/l32lmII1jO+3gUmrUg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
