example_key: ENC[AES256_GCM,data:odJ19TmTd/7C2xF6zKs=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:TmIcJQZpgyVHu4YNb0QQ3A==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:SNR1CkSGmE4ao9LHZInVejLBf8leDNiefgiq/TXWvDf10dVpt0imBn9YLJBjZtKm7IqjhJQx6NWQh3bTLRBUQcsCczWe1KoVl7eVmzG/eLTQ7AgRdAJl6oIA5whbXzT98PY0VE/rLL9S/rparS1S8hPWwp+xwNTl/eoY5mNR2ER6lY8/42dMS86UOj9TK503NW/76OE=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:DcMC3vy0Y1GtVGM4Cc3LGQ==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:WKfrSSMmLFh34388Bs+sfINMNGxtUkEuHWMeh0of3K89P2vw5K+z5YXspeuD3Eh5B+mfwkdbUMgOrYdJnFE6o1crLjfdpHpcRZjqxqnR0LIUZxw4QBWYItsJOcL9XBh3Z3i/hlaJHkIGk3ZBoeleNhJQHAxQSnegljVqVCZaVHSwEHhkjkzqOgNQpQJPSvBFdxdjaS4MOqpwnsdpSAoGmnTxyi4PuKxmZMcA7lGK4V8n1jGkJ2i3mcTViQZJtk6DKBB5Ws/MHLHF2GkKhBw+Ianmx5WRO3d8jPbuLz85cOQ24UgY3tehjRrj/rqTljZH4bqbWv03I2Wub9iJp49xsjnKo3htD1bUkZkalOGYmHpP10oAC1lsgEXexdooPg8MKNJ5MAzPYb3VFM9crseKLhGCUoL4gjEbnXZoeIYIfhjGbXWdsVb/Ei0m4FFdjjlphpwrGeYDSsA1oc6MkVqXgDX1Qg90V46Wmd8dsS/0M92jiSmcFF+XHjl3OLSpxqYV2QgVCMscXj/brRqccMkXuEtWV8SCLDe/q/c=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:/3vG2aRZLWc0/Xw572ixsg==,type:str]
atuin_key: ENC[AES256_GCM,data:RoDLW3wNsmxk0VFBztlj5kOgd1ukw7btJbLTFqh8y1kFx/HuFk3X/6vLmFLG05eKLbS00f7yofBwqMShvQalJg==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:9ppx2gw3ZT4mapp5v/Na4Q==,type:str]
env_credentials: ENC[AES256_GCM,data:rpTKCVQTTKSA735zs80lnQh8r9AHf9/0YvzKaGS6Cy1NeqVKyXf+reRKu8cWJtO/eqkqS0zLkffCqaEkUoJ+52rAOHRQRuAGfl0sLmBBES48mO/NJqmXRM7W1pJ07glGe833Xx/GYl5p0n9JQUQ5bOkGF9gVPcKgXnYuugNWHoGaacqtU1G48UIIN97K0gD21w3Cmk9v7PaEaNG2RoE699+SR0VSqJLdi+uHbT3NFzzECRtptQu3UA7rkuyQZ8WjH6DTbpeqkcxL6SU3DZWqlqt78NUKYcsm/O46666JWul5IvHYU8xnC/4Yh4Gc+/AEVQ8xIxHBQxu6yX+TxT5pMVZEZM3aj+Y60tSC1l9iCWmG/xDo6JObVDfPR+AYgQAyQHI1dy6bc7Q9gIu2fBAb2tM/Ay9bQ0X/jlEQwitWTFIcU16tyMLou7OjIxZ3fhJK5R0UPIkaHRYVyU8kQ25gilieuMJw/X5/x5PfDZr1LDeuv0d+IYgYUMFyJ99Xco6cNMlpYu3pTKgJZNo6I7SPi87W3/8z80dxmY/pKlm0M7nMMWHZ8aGfSsJu8tlneNt0tDOO5vd6z5I1eH/L0Af/nnnJJdNI4yMmExOr+Azkm6gSNiORckcqsemzwOUk+sRmPOM+B+09/VfGND/kkwnbzQ8oN2PbCMzoSZK/8mabKLnu2e0U8MP2OmMcIHHAKv2FkujMVzqv94Qp8JRad3nBxxyFemY27ktEX+T1goJ7lkjYQEiHAnAvi5XXgTJAL8C9DrUl+T/D4BERSSRBz3NNcjtYPmQlUqJHS0FckXTcC6tzPP/WEkGp+fXlNoIcjTmsKpTkjUuQj1XPLgsrnPJRHjaWOAnmn3crd9nVKY6obyEdXjMQhXVfU6WYOiAKOUzngS5P09dT2eEMicNhjZAro2FqLGgh0nJ528YpmBLkAp/soiUwbVEagmzkvjFpWvAh4ajYQpBP0u7BTpZPbXvDDw5ax9Gurlv3sw==,iv:jHMQCLU7vGE6+qpY3/k66GLZDq69r8szNXSIE0s1Tu0=,tag:t2cASVWMbLtqGE9kKsKrLw==,type:str]
sops:
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelZkd3ozT2JMekQzbC9x
            UVVyVC9ZUCsvY0Rra0gwaUdobFhNbGs4R2pNCkdjeFJ5dnRsTHR1Rm9DaFZhVEZx
            Mm96MSthZnJMVG9HUjgydXVBU0hGMkUKLS0tIDNSTC9xZTZPck1tb0NqRm9VTlNH
            QkhZblhqL3U3eWlDSGJ6cWRZZnFndjAKRRjXAA0MWM/yVP/YCp6MLjpcUAHujO0I
            9Wbrj+S1QFyYLcnnOWLz/t6uW1LGYYcGoF6col/d/s4X5jP2XBDRKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOC9VREN4emZuRDRtamlY
            TkRpbENqUDVwckZuNktmYWdMRzVpNXhvcGwwCldDVXV3TGRSM1p4WlFaK01JU1Vx
            eXMxcG0wbXJIUGs2dGgwY3RRSU90NUkKLS0tIGNSRmViSmJxN3BaNGlhZU5TdEh4
            clhTczZPQlV4SlRpMWxmR1ZRSGNjelEK1E2UfiOF+CR/BRxnyKnDlKdSJY0OmZJS
            fAgLzdysQ8hBin54xbtWgx/XJ05d4k4qvILawm2mKn1kHBoE5TYLrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVVLblZWM3pnV3pwUnl6
            YjNvQ0RjdzEwQnpnMW9tUkk5ZlIzOCs1R3pjClZpSVVIZXcraVpPQ1VOTGxnWVd1
            aWk1WmFuNHFxdHplK3Mrc2EvVXZTbncKLS0tIHFNL3ZqS1lub2ZMMmgrc0FyRERN
            b2UrUmttRWpraXlvNnM3cHpUQ05kdE0K/d4bfnX1TWC6MVUnOIUBO+LggNQkJzxi
            6l59lA98hEHyiRzWrb0DUOkNnOt5IVjblawzoUZ2EMW3DplGmAfRZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n3q6hj36mkzxntdl7zmws7l7zna8z8f930h2tj00vwc2lucszyxsdd4pzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaXNGYU1RRlFyRU9XQW5S
            czFNUUZBNkgrZHhFNkFmYlZ2ZmZQNzVFd0ZNCllEN0trZU84WUdSQ0FOVjJydU13
            bHBaM2JMTG5qbHhQRjNUTlR2NlZ4aE0KLS0tIGFqalp6TnBBRE83dFBZQTRqU0Jh
            TVU3ZFJZdzBZcVNrS0ovUUJTcUFzTHcK702Py//lPVGqfr0e3JCAidlowEnfv85T
            uvITbaZR/1H164zBpmkPRHaoxCGLv1u86cxJKmcELTU0/1GHNztI3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-05T06:36:10Z"
    mac: ENC[AES256_GCM,data:7IBqtKPh9J+WE+2Gpe2z7vO8pI4HCH0p/t3CQ+lT9hQt3RLRg35B6LuFZ8rjSgrNeDM3tgJpJMvxtn/nCpKSCVngs7QoXJqeur/3/wDhTrqmEvb1oFGEpjnLXKX0prfya7z7hGi9d3s/NnUDk/vrhsWs8Kfv9LSax+MilfdtQJI=,iv:g7ZfrH3ruYF4sdcJKexs/o7pdIxcqKZ7KOc+0Hlvq00=,tag:uH3P5GJV8UImIXt201ZERA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
