example_key: ENC[AES256_GCM,data:wqWaxRvSxyu0EC+OoIA=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:6LbuWPrDdBGWrtPQofX4qQ==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:bek0JOBoFBdB3seNrBwNbv5nvTkdmfMIWpjTZDi42XKef9dLeTUvleu+L3lhtgtwIfq7BqFfAN3ZyRKMQCF2yPxC11EEP2eWdNA2yAPvPiDnO4ig3XvGBAOinZARdH86fVyEj48WxSDWjoeqpMfS1gMaDFxad+CiX0M8FDFy3aqWVUQONnQF/0FxVqWPNGacrkvO8C4=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:HrZy9xH3fxRUSMsfPYx5iA==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:eClT/xFOpZVIx/GU5pSCFTnbFJZb3nWNFK3ksS7meLw/I9Q7+uYwt2Qka0vgFJgOBUG9cpsd7J14Nkbg6tPD59dgChWZHBI1MiHZixoIv4CHEfTsNm8WnBoQgT8nMrtcAOiKxvpSoAEUCiJOg/+TwZBcFeD0QPA3W3/11+OO5LAYlL2tPlmcAIxBHpVrT8WSLDGOaQcK/E7ezq693ea9N+SxGisjYDSRwVWkz8keye+2pz+SvF2t9Kobtn7PyPHl6Iy9awjS8jEacXCQRo9XUgpChwumaV013K2o1PQlT4nVdPCzOkyYHXxHqxLxVTkMhKzPEmyr8eT5FpvH/pFHvZWPdeH/hEJ7iHr3XJbeLngFGrJv23XlYNJxK+HKLJbtv62htubamqUQK7cTPDvCRzNBgH3hlULXZ9PC0Nm/BFgRVE5mymlocmL9MdTtkj/tyELVdh4bhNMnHEvuDU8YzDVpAvqQASZy9uOns4BhdJ3goDptFepdngmGyN5DWj1ADTVbbV4XSlEquG31qjD0W0Bf/DozzeXMoMQ=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:obzRqaZIMzck8ORscgoa8g==,type:str]
atuin_key: ENC[AES256_GCM,data:+dzNxAyJP/d7FrH8m8DGtu6dQSRn0fgkU/XwobmswOndtaUXYltvbpVJ327G0YMKlrIngD6P6lsRw1cw36CFcw==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:akx1j4hOGu2Si4Cn3xIEmw==,type:str]
env_credentials: ENC[AES256_GCM,data:LAuB+awQxBjc3HDxZD6M0kQdKFJ3qRTc5/4i3MRcJSGPbSUHPKt/7jULwS0BVKiTlvwlIpd1gxm5QbhKBhvrZM4OaYCYumX4xmEHjyV64cA8QLZIyKe1g4KO4pDc96q3ut89Bd+yc1fv0rJRmWmemsG3fSsAluPuVVsdblr0ibHlNq3oJwTUBIFKrYt1fLYSedUK2nFLb/IHXWB91hlk5dD8vdRPVsTgNvQvQv+kp5TOyUnc0m/DCXGolif3pemeDu1n0sKFSvU9oBUaLAZvLewE6tZXCIz8d3eZuX8EIJss4hxZ0A8uA28pComvMM0uV3+O9e4aWgYbiYVi5mn9Fs/OmSDeJoIB+RSVMEI0ngw2xavVGQJagRqZm6DPH2paqs34zrKyP4aIRXT/dK7+llqdfEV0LMCOx9clkfrj+mfZmMbadXQcG04Z3dnt5mMdcZj4sq18o04IxuAJOXUdBIOofduUF2yq//vYLIOM6otEtfqG+VAxI0o5SbSG3UZCKDN8aVb11gEurd+3857cYOHZFPEmu969TDjGq/wjAV09MCtdPrXT16uEwBh+yFbA9rL85nPXdKwTzHfdPGP7,iv:5UHJc3J0RnzQY+1OYEk3pQFVFbTxPuHDDB5Raw6LLbY=,tag:MGdS60PKcEty3NZK7sk5hA==,type:str]
sops:
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQklpSVdrRkFWKzVhb2l1
            UEpzL24raWh5czZXcndPYW9HMSsvNndwS2lzCjA2MHBTeENOOHRXWVdDSW9zWkdK
            TTZNeUlyTGFia3RXUVlSUUpvYnI0dncKLS0tIHZOZWRVWXJFRW5sRG52OU9qSllm
            T08yaWs3QWhibWZnbis3TStqMDJaZ2sKGP2JBKr8oEPVDCvicdWO2KcrbXCxlmES
            ixCGnq/WIKaFDLYVlkWG0zYVSa4y0zhm7Doyc11Ds1wLNH2x04rMOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSGdWMDZybWJjMzJXcEd5
            VXhwd1JIM1dqRzVUOEM2MUtXZmVGaFdRbVNRCnZOLzhyUDJHc29ha3ZHYzUvTkRr
            aFFLV3pUYzZLbEM5cTBMQkpoQ3QvaWMKLS0tIG8wSG1TeXRjN25rMklEM2dZZGs3
            cnJMVGw1WmJzdzNOa3EzZ2VTNjFEN1UKonuTcdX2oCfvue+pIYb8tPkin0p8mWuE
            oHqlczh92+G+V4cedtdAx0vQN49l9tKUf1v06zC7gCHISp53iCXUog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15drpfd2kkm32g23wef9ptzyy8slrzhyk5cstwnn5pdlwtt37cqsskx2l2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNDExaFhDY3Z0bkpCRmFR
            Mnp6RXIzaVVMV3JRZlA5ZlFmUnkwajhwd1cwCkZITi9NdG5RWXpLMmFqMmVkbXFV
            ZnUyM2JGYjh1aUVCRGhEd0luLy9Kb28KLS0tIHkzRkt5YzFhR2xWMzVBWXlUN3pY
            Q3R2R2YxY1JkMmwwNFdHQTJzd01yOGMKaL7UXRL1T4Ugn3c7Zb0cEZcu6G3CZRew
            XssaYhZJTVJNNbgukl6rfSEqP6hWSl4iry6p2lmPzP/5jLGaxOJ3Qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mv05td5h3m8wa3cqxm0npepn8jlqhrvsk9pcaewj6lmqzzew59mqwqyats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzKzRRQ0E4Nm9lRDk0WTRj
            N2dsUks3MGhlcnpSSlFjd2FvQ2svdWQ5cENjCmgwOUhCS05DUTk2UjJnUUlFTmdx
            Smg2OG8vUmd3V0ErOHNQOW1RNXVmNmMKLS0tICszYXZ4YXlzOWszY0pjd3JYWW9h
            UU44VDhGNzViaEUxUWI1b1V1bVRqY2MKkWBCvBc5tIPLhKgQwjWDRtxwBhSQdZOd
            CXgoqpNqlR6mz0JSnuIyjzs9CnM1pTeLGjq2fX+wE4H9nLPQbSQkKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-14T10:29:05Z"
    mac: ENC[AES256_GCM,data:d6SyDvbkqXKSB4qI9f9XvqfueuGc+wC9u4saX/sBQtpqDCYCABaDIUGR+Gmixy1WEXMhQAt1mVJLe+DmVI/w0Dhnal0CeDLD9zCnP7pTcKMwRBMH4FploOhLytwvsxXCk7D5sb2W7nn/6Ufi/4z4WknlRMGudGx8nBd3p1Mirm4=,iv:/6AmogH5F17V/ty7l2ELZNu4UY75KLGpHdQLSZdLb10=,tag:jHaQS4ghbR8u1rLKkEIjCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
