example_key: ENC[AES256_GCM,data:odJ19TmTd/7C2xF6zKs=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:TmIcJQZpgyVHu4YNb0QQ3A==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:SNR1CkSGmE4ao9LHZInVejLBf8leDNiefgiq/TXWvDf10dVpt0imBn9YLJBjZtKm7IqjhJQx6NWQh3bTLRBUQcsCczWe1KoVl7eVmzG/eLTQ7AgRdAJl6oIA5whbXzT98PY0VE/rLL9S/rparS1S8hPWwp+xwNTl/eoY5mNR2ER6lY8/42dMS86UOj9TK503NW/76OE=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:DcMC3vy0Y1GtVGM4Cc3LGQ==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:WKfrSSMmLFh34388Bs+sfINMNGxtUkEuHWMeh0of3K89P2vw5K+z5YXspeuD3Eh5B+mfwkdbUMgOrYdJnFE6o1crLjfdpHpcRZjqxqnR0LIUZxw4QBWYItsJOcL9XBh3Z3i/hlaJHkIGk3ZBoeleNhJQHAxQSnegljVqVCZaVHSwEHhkjkzqOgNQpQJPSvBFdxdjaS4MOqpwnsdpSAoGmnTxyi4PuKxmZMcA7lGK4V8n1jGkJ2i3mcTViQZJtk6DKBB5Ws/MHLHF2GkKhBw+Ianmx5WRO3d8jPbuLz85cOQ24UgY3tehjRrj/rqTljZH4bqbWv03I2Wub9iJp49xsjnKo3htD1bUkZkalOGYmHpP10oAC1lsgEXexdooPg8MKNJ5MAzPYb3VFM9crseKLhGCUoL4gjEbnXZoeIYIfhjGbXWdsVb/Ei0m4FFdjjlphpwrGeYDSsA1oc6MkVqXgDX1Qg90V46Wmd8dsS/0M92jiSmcFF+XHjl3OLSpxqYV2QgVCMscXj/brRqccMkXuEtWV8SCLDe/q/c=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:/3vG2aRZLWc0/Xw572ixsg==,type:str]
atuin_key: ENC[AES256_GCM,data:RoDLW3wNsmxk0VFBztlj5kOgd1ukw7btJbLTFqh8y1kFx/HuFk3X/6vLmFLG05eKLbS00f7yofBwqMShvQalJg==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:9ppx2gw3ZT4mapp5v/Na4Q==,type:str]
env_credentials: ENC[AES256_GCM,data:zFxvFzwPsO47EBnzDyrV0Y5pek6ZuM2oAJa0im91m0dMXHoDoX8qNQZJbq6lsbbhB2hhX9ZMF2iEzh1180jKAe5hq7X547/yYU5P39GqoIrv95TsobXsX9F2FwAEkmMyHi2lg9xRktOFTxlG86zO4/rFA38q1AWMfZHlTx0gXt4sOZD7XKF7i5LyREbobhPf+iGLGYSU/vmSLEt6KUqb+EKyA8MOVBnpysum8CQMisq8tHYku7nbNsMdTInB2lMuKOkNFCo40/cS6BsM++vYUrCUtu3Oa9amXrViDXf2fF+mYcYvSXu/kvXx+jnnRSg8soB/CpYE0DEIYxDZBvctfdV7pxLKkbcvrzyi8U4czu5V5Xb2PJPrvVuEf9ZrzEEzfY4v8sFjKD12b2lHPa5k7+x5GbvNmVe1OEZRUHdyyUDg38ZmT5+hTH0/0hSLHQkTf2yABsweSJirdW26j6t/5sJ3aMUmrIX1TOIbEGfg9N1Etl8U2Y8i2sQQ0tsuiS42zdHvMP66ZGweAxH6bIs4Lj78Dy6boxWJc8TPOlP0T/3sl9Q0UIlxq4KYkgPEaikYQnEnzyzamY4oH8b7e6+2gslxp/zswhDnVvrCt6F5h7MBcyO+uXogLj+zFwCRvy52wflwmxuLSZmo8FTLvSJxVyQ7VIRZo8DDaEQBqsfu5jVmW7GlJqxSEhlXgAWAslb0gkH1nORhSP+O5jsLTSydgj/wIkdd7j0vvGqesoi8bSOIf9F2ddI29+FL5F7qb5t3iaSLKJdcTxdmFCwTKNmQuyuorzl4pVAM4J9VjWSSLLgioo7WlItIUejhlCQ6uUwd2UUHXG+JQcHD/RG6P6IrQLxMdVFvhdizz0jDydbS2Ujz8hsnfIkcH/7dIjeW2WuUMRRlqUoDU/Bzze42OKJa,iv:0VWSih4qh+oCvV9ra8j6sRfMcqA8T2xDt6YqbpLedmY=,tag:pGvJmmoM8btf/tThzbwiYQ==,type:str]
sops:
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelZkd3ozT2JMekQzbC9x
            UVVyVC9ZUCsvY0Rra0gwaUdobFhNbGs4R2pNCkdjeFJ5dnRsTHR1Rm9DaFZhVEZx
            Mm96MSthZnJMVG9HUjgydXVBU0hGMkUKLS0tIDNSTC9xZTZPck1tb0NqRm9VTlNH
            QkhZblhqL3U3eWlDSGJ6cWRZZnFndjAKRRjXAA0MWM/yVP/YCp6MLjpcUAHujO0I
            9Wbrj+S1QFyYLcnnOWLz/t6uW1LGYYcGoF6col/d/s4X5jP2XBDRKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOC9VREN4emZuRDRtamlY
            TkRpbENqUDVwckZuNktmYWdMRzVpNXhvcGwwCldDVXV3TGRSM1p4WlFaK01JU1Vx
            eXMxcG0wbXJIUGs2dGgwY3RRSU90NUkKLS0tIGNSRmViSmJxN3BaNGlhZU5TdEh4
            clhTczZPQlV4SlRpMWxmR1ZRSGNjelEK1E2UfiOF+CR/BRxnyKnDlKdSJY0OmZJS
            fAgLzdysQ8hBin54xbtWgx/XJ05d4k4qvILawm2mKn1kHBoE5TYLrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVVLblZWM3pnV3pwUnl6
            YjNvQ0RjdzEwQnpnMW9tUkk5ZlIzOCs1R3pjClZpSVVIZXcraVpPQ1VOTGxnWVd1
            aWk1WmFuNHFxdHplK3Mrc2EvVXZTbncKLS0tIHFNL3ZqS1lub2ZMMmgrc0FyRERN
            b2UrUmttRWpraXlvNnM3cHpUQ05kdE0K/d4bfnX1TWC6MVUnOIUBO+LggNQkJzxi
            6l59lA98hEHyiRzWrb0DUOkNnOt5IVjblawzoUZ2EMW3DplGmAfRZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n3q6hj36mkzxntdl7zmws7l7zna8z8f930h2tj00vwc2lucszyxsdd4pzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaXNGYU1RRlFyRU9XQW5S
            czFNUUZBNkgrZHhFNkFmYlZ2ZmZQNzVFd0ZNCllEN0trZU84WUdSQ0FOVjJydU13
            bHBaM2JMTG5qbHhQRjNUTlR2NlZ4aE0KLS0tIGFqalp6TnBBRE83dFBZQTRqU0Jh
            TVU3ZFJZdzBZcVNrS0ovUUJTcUFzTHcK702Py//lPVGqfr0e3JCAidlowEnfv85T
            uvITbaZR/1H164zBpmkPRHaoxCGLv1u86cxJKmcELTU0/1GHNztI3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-08T15:24:42Z"
    mac: ENC[AES256_GCM,data:d1p/E1RyDTemQR1pXP8wvi6Zm3+4zdusYvHeaX5M/N28vcZGOKvMdPkUS9JU7SsU2zmnpUm3w2qmK5yD4SZg+7pr0OzuPHCBoZrCapm9EsUlnjWYOnfVW85OjGvyO8LLr0iTQq1ixC6sHgXIYMkVWAFYmf3RkuNtEPGbtc+9I4o=,iv:+IMKLzWbBk7PP6hgYpn0E5ecAj5PIENd404evlV8nMM=,tag:0J9k67+u7/0HHXc7Jk8eiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
