example_key: ENC[AES256_GCM,data:odJ19TmTd/7C2xF6zKs=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:TmIcJQZpgyVHu4YNb0QQ3A==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:SNR1CkSGmE4ao9LHZInVejLBf8leDNiefgiq/TXWvDf10dVpt0imBn9YLJBjZtKm7IqjhJQx6NWQh3bTLRBUQcsCczWe1KoVl7eVmzG/eLTQ7AgRdAJl6oIA5whbXzT98PY0VE/rLL9S/rparS1S8hPWwp+xwNTl/eoY5mNR2ER6lY8/42dMS86UOj9TK503NW/76OE=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:DcMC3vy0Y1GtVGM4Cc3LGQ==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:WKfrSSMmLFh34388Bs+sfINMNGxtUkEuHWMeh0of3K89P2vw5K+z5YXspeuD3Eh5B+mfwkdbUMgOrYdJnFE6o1crLjfdpHpcRZjqxqnR0LIUZxw4QBWYItsJOcL9XBh3Z3i/hlaJHkIGk3ZBoeleNhJQHAxQSnegljVqVCZaVHSwEHhkjkzqOgNQpQJPSvBFdxdjaS4MOqpwnsdpSAoGmnTxyi4PuKxmZMcA7lGK4V8n1jGkJ2i3mcTViQZJtk6DKBB5Ws/MHLHF2GkKhBw+Ianmx5WRO3d8jPbuLz85cOQ24UgY3tehjRrj/rqTljZH4bqbWv03I2Wub9iJp49xsjnKo3htD1bUkZkalOGYmHpP10oAC1lsgEXexdooPg8MKNJ5MAzPYb3VFM9crseKLhGCUoL4gjEbnXZoeIYIfhjGbXWdsVb/Ei0m4FFdjjlphpwrGeYDSsA1oc6MkVqXgDX1Qg90V46Wmd8dsS/0M92jiSmcFF+XHjl3OLSpxqYV2QgVCMscXj/brRqccMkXuEtWV8SCLDe/q/c=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:/3vG2aRZLWc0/Xw572ixsg==,type:str]
atuin_key: ENC[AES256_GCM,data:RoDLW3wNsmxk0VFBztlj5kOgd1ukw7btJbLTFqh8y1kFx/HuFk3X/6vLmFLG05eKLbS00f7yofBwqMShvQalJg==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:9ppx2gw3ZT4mapp5v/Na4Q==,type:str]
env_credentials: ENC[AES256_GCM,data:QR2L5uGOxNOzEEvDkeeF4Bw+Vuort+/Pqhya5Fl29zBEqLyW+0MkO/9gE3bal7v3ebHGsw2cMjwSeDqxrFcCQbTN23NofxoS2f0e5mYacoVCqQze2pfHq6kBBCLUwRMMD9sipTmnO1WbXIZ0lka9ZXny25H1feXx8b7idKeGval8WjJtMv18EGeLG8PJLDgpkOpyz/dldsHsl0BlB2MUEFAEvmLmIkrGxaV8c65CPVaaIazlVsXq+UJHSYHhfyCEImfjCm556JEXBf60xij24JPYAVpU9Z3lTnvsHYD0Gsi+8KdeIf5YPsVddXjdNJsQ+a7CXcorhKFOSfD8sqZ4XdtQKwfSh5xVioLL1IcZ05kWDQutsEzetTI2A1zih12TqxpkocbnzteOhZeBU6FNMeGnHfXskgAcNfHg86w/YSX+AfxMo6/J4FS1JV1iqph4F++/o3EspL6iow4hXCWipFn6Hsx/KObXRsxxMj9iL1eTe+lhlAZ5hJUSfsVZ/oWpjvY/FUjv2kVKR+jsAEbEmlznAf29yvVYjLoZCD20AmbHDCyXXQk0uBf5GblpiqYOUMTclDPrJjqfG3EVZWT2jEbEgBS0vldDIKWZZ+5FWvSEMcuU6IsK6LHmAeM4st/EywVDJB/SDgaUBVOETahfBGiNdzedy7JkB5aCyAhoaStCvO53qmEzYKl7UOxLHfUFAvOKfbqR57ML7Y0VXhwHzeQiFol3MaytT3Xd9A7bHHwAbX7HRemAvZdKaOzY+boxqEPa1GWFQoweNBJLmOxzlGBzylQZqzmbSQF15gAnvkD7uQ1rWG0vBbEF7kN3FC1HODZ0XErf79jbrAtfDBf9lto4RuI7j1NSsCSwFnKsGpBY+hxF1pjRDPdYhCJBS8DnjZEWpr4UKNtxBjKdryGnvid3BNyfYv+gj3auRrd5etQjoR5lekmM5ID+FdgRNTNSjWPg8APvm2HjgVlmQ0SFfQ6iGXcYE+2KijZszkyKQdpHVUGE+yHRVuyBn2dqvZI3yXy094BLt80oioxCOAkd0PLpiL6w7xuuFdSH5wuNUD+t7K3wLrm1UCFQIRSpBYMLu5sgsRlwOd8/06sC+h9Uwp/Fhbs1FAMZlUjDK762jMaYlucx8e9RGQQO8wBGQQ==,iv:xcD5pN4F5s4VZn4VkBlbyJKLCKzNgwrtz7G5bkkB+Ag=,tag:xebJmdkiSKYHVFJf6JlJwg==,type:str]
sops:
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelZkd3ozT2JMekQzbC9x
            UVVyVC9ZUCsvY0Rra0gwaUdobFhNbGs4R2pNCkdjeFJ5dnRsTHR1Rm9DaFZhVEZx
            Mm96MSthZnJMVG9HUjgydXVBU0hGMkUKLS0tIDNSTC9xZTZPck1tb0NqRm9VTlNH
            QkhZblhqL3U3eWlDSGJ6cWRZZnFndjAKRRjXAA0MWM/yVP/YCp6MLjpcUAHujO0I
            9Wbrj+S1QFyYLcnnOWLz/t6uW1LGYYcGoF6col/d/s4X5jP2XBDRKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOC9VREN4emZuRDRtamlY
            TkRpbENqUDVwckZuNktmYWdMRzVpNXhvcGwwCldDVXV3TGRSM1p4WlFaK01JU1Vx
            eXMxcG0wbXJIUGs2dGgwY3RRSU90NUkKLS0tIGNSRmViSmJxN3BaNGlhZU5TdEh4
            clhTczZPQlV4SlRpMWxmR1ZRSGNjelEK1E2UfiOF+CR/BRxnyKnDlKdSJY0OmZJS
            fAgLzdysQ8hBin54xbtWgx/XJ05d4k4qvILawm2mKn1kHBoE5TYLrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVVLblZWM3pnV3pwUnl6
            YjNvQ0RjdzEwQnpnMW9tUkk5ZlIzOCs1R3pjClZpSVVIZXcraVpPQ1VOTGxnWVd1
            aWk1WmFuNHFxdHplK3Mrc2EvVXZTbncKLS0tIHFNL3ZqS1lub2ZMMmgrc0FyRERN
            b2UrUmttRWpraXlvNnM3cHpUQ05kdE0K/d4bfnX1TWC6MVUnOIUBO+LggNQkJzxi
            6l59lA98hEHyiRzWrb0DUOkNnOt5IVjblawzoUZ2EMW3DplGmAfRZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n3q6hj36mkzxntdl7zmws7l7zna8z8f930h2tj00vwc2lucszyxsdd4pzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaXNGYU1RRlFyRU9XQW5S
            czFNUUZBNkgrZHhFNkFmYlZ2ZmZQNzVFd0ZNCllEN0trZU84WUdSQ0FOVjJydU13
            bHBaM2JMTG5qbHhQRjNUTlR2NlZ4aE0KLS0tIGFqalp6TnBBRE83dFBZQTRqU0Jh
            TVU3ZFJZdzBZcVNrS0ovUUJTcUFzTHcK702Py//lPVGqfr0e3JCAidlowEnfv85T
            uvITbaZR/1H164zBpmkPRHaoxCGLv1u86cxJKmcELTU0/1GHNztI3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-29T05:58:23Z"
    mac: ENC[AES256_GCM,data:xLJuae07HHTkHLdG6TS3Cibej/W0gI0jUm0+Ed+z2YR9tW89fPihp7GHyc7l4I5ThCLuDOQvajh0rUeVsb/neagd4FCTXpuG5l/r9lKNQdxp26KvHBrT5cW4Q1i/jgb5zxN00XEiTBXOoDbpjiv9eKfqFaLVMeD3mx0qkhOXJjM=,iv:yyPz57XMVHjcQg1ATNGEXSZQhuFQEIby3Y2nPX7nlYI=,tag:pzI89dyWyXUYY9IGEif0aQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
