example_key: ENC[AES256_GCM,data:odJ19TmTd/7C2xF6zKs=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:TmIcJQZpgyVHu4YNb0QQ3A==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:WKfrSSMmLFh34388Bs+sfINMNGxtUkEuHWMeh0of3K89P2vw5K+z5YXspeuD3Eh5B+mfwkdbUMgOrYdJnFE6o1crLjfdpHpcRZjqxqnR0LIUZxw4QBWYItsJOcL9XBh3Z3i/hlaJHkIGk3ZBoeleNhJQHAxQSnegljVqVCZaVHSwEHhkjkzqOgNQpQJPSvBFdxdjaS4MOqpwnsdpSAoGmnTxyi4PuKxmZMcA7lGK4V8n1jGkJ2i3mcTViQZJtk6DKBB5Ws/MHLHF2GkKhBw+Ianmx5WRO3d8jPbuLz85cOQ24UgY3tehjRrj/rqTljZH4bqbWv03I2Wub9iJp49xsjnKo3htD1bUkZkalOGYmHpP10oAC1lsgEXexdooPg8MKNJ5MAzPYb3VFM9crseKLhGCUoL4gjEbnXZoeIYIfhjGbXWdsVb/Ei0m4FFdjjlphpwrGeYDSsA1oc6MkVqXgDX1Qg90V46Wmd8dsS/0M92jiSmcFF+XHjl3OLSpxqYV2QgVCMscXj/brRqccMkXuEtWV8SCLDe/q/c=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:/3vG2aRZLWc0/Xw572ixsg==,type:str]
atuin_key: ENC[AES256_GCM,data:RoDLW3wNsmxk0VFBztlj5kOgd1ukw7btJbLTFqh8y1kFx/HuFk3X/6vLmFLG05eKLbS00f7yofBwqMShvQalJg==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:9ppx2gw3ZT4mapp5v/Na4Q==,type:str]
env_credentials: ENC[AES256_GCM,data:Ou3MO1dIQW3qv4YUBKjJbS8rURyPGXEn8UNgl4D2oBSV2hDgw5eTFPwxEZuct6BZxSRvBvROJD1NsRgAkKuZnc7ELIp5zdgMEWLzFhHyCY7bcI7wBgwA67Qw1e7dW6myCENc5DO87P3KJD6typPZcjysYsYLsupgypPV+b9+6qtp+GmKg4QtTH4MoCPSlFLb9Lerv1bSyJYtudNyg206mhPd0Uil0iL+iGihpldoZyiNYp5/2oVVcoG/PWQxGTvHjRXrejo3bXrMSNybHwiMSTblpLOIulbpIij4cTcaXutzfG4hmxRr/z6uFSnWFS7AqCvi25Nbu+74y6rp8AVr1Btyi9c3oxnZ23YngqRfAQWhz6z3eMEh5bzQs0fDvVjVvtdE6IBAQLZaiI1EH4/qd5efXmZOe3MQMle3U2RV+aho23IK5ssqTolS1kQFEL9vBs5Arru6kmufN3HGxOYtvDj8o/5jrdceq3R22fIaaBI2PC/FxLs8iEcQw4aVO/P9M4YORIia1Z4//Kw47HqoDuXV5a6LT2CmGbBVchmo4wfxL2+UyUokFFmtpsEWqaVv+t4LF3oQ3ck/qwWlsSj+LcGD5RlHixIto7c6RF/X0c9JBQuw5NU0C9Zjw4AT8Bz7HTiageAxuyF5EwKtMNaJKP3UGHFeBjNK8s+mMTvnsiXy1hQEdMaz2BHINOFhfPFXbGa6yXGw3XqS37BGxtneeTsXaod1833Rf1xoVoZnlhAHDbKblaPhdhONlcBAdgKvGaLwgordYutmxyTrVRw0uga86cOqWfmrXWcltOmgxEGUEOhywiTEZwlJWvIIpQ==,iv:7KlXoZUFfy8gK/Y7cdmLi0K8XLrFLawh5BsykOyDG0A=,tag:tGh+GDMcvZept85DZqBsaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCelZkd3ozT2JMekQzbC9x
            UVVyVC9ZUCsvY0Rra0gwaUdobFhNbGs4R2pNCkdjeFJ5dnRsTHR1Rm9DaFZhVEZx
            Mm96MSthZnJMVG9HUjgydXVBU0hGMkUKLS0tIDNSTC9xZTZPck1tb0NqRm9VTlNH
            QkhZblhqL3U3eWlDSGJ6cWRZZnFndjAKRRjXAA0MWM/yVP/YCp6MLjpcUAHujO0I
            9Wbrj+S1QFyYLcnnOWLz/t6uW1LGYYcGoF6col/d/s4X5jP2XBDRKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOC9VREN4emZuRDRtamlY
            TkRpbENqUDVwckZuNktmYWdMRzVpNXhvcGwwCldDVXV3TGRSM1p4WlFaK01JU1Vx
            eXMxcG0wbXJIUGs2dGgwY3RRSU90NUkKLS0tIGNSRmViSmJxN3BaNGlhZU5TdEh4
            clhTczZPQlV4SlRpMWxmR1ZRSGNjelEK1E2UfiOF+CR/BRxnyKnDlKdSJY0OmZJS
            fAgLzdysQ8hBin54xbtWgx/XJ05d4k4qvILawm2mKn1kHBoE5TYLrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jdhfmp60w854vyg335p4982fqq9l5khdmaulsze0ywn9kupyypyqwm4ww8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bVVLblZWM3pnV3pwUnl6
            YjNvQ0RjdzEwQnpnMW9tUkk5ZlIzOCs1R3pjClZpSVVIZXcraVpPQ1VOTGxnWVd1
            aWk1WmFuNHFxdHplK3Mrc2EvVXZTbncKLS0tIHFNL3ZqS1lub2ZMMmgrc0FyRERN
            b2UrUmttRWpraXlvNnM3cHpUQ05kdE0K/d4bfnX1TWC6MVUnOIUBO+LggNQkJzxi
            6l59lA98hEHyiRzWrb0DUOkNnOt5IVjblawzoUZ2EMW3DplGmAfRZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n3q6hj36mkzxntdl7zmws7l7zna8z8f930h2tj00vwc2lucszyxsdd4pzl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaXNGYU1RRlFyRU9XQW5S
            czFNUUZBNkgrZHhFNkFmYlZ2ZmZQNzVFd0ZNCllEN0trZU84WUdSQ0FOVjJydU13
            bHBaM2JMTG5qbHhQRjNUTlR2NlZ4aE0KLS0tIGFqalp6TnBBRE83dFBZQTRqU0Jh
            TVU3ZFJZdzBZcVNrS0ovUUJTcUFzTHcK702Py//lPVGqfr0e3JCAidlowEnfv85T
            uvITbaZR/1H164zBpmkPRHaoxCGLv1u86cxJKmcELTU0/1GHNztI3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T06:56:52Z"
    mac: ENC[AES256_GCM,data:J8NRSMAMGuxGAgISVSu4Dv6vPUeoPRmJynxL/DIztjsmRa7rmcpf+uiU7d5YCTuepFM+1JWFYQiS4MISjq+L1T6pUu+7wH9nZbh98Fi/XJ2o3Xm09seEjYeTTRXiSVumizSpdXF/mqmhqVRZMKNWopvMMqjlMf7ycVGSrnevf2I=,iv:/nsqJCV1kEwLne7vo/WdM23VMrymd1f8ZLQECrrHr2Q=,tag:cVIfqr8qHaG/VHtuA+gI3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
