example_key: ENC[AES256_GCM,data:FoIx/kdpuqhEJJNojGE=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:MG4Im9DSMgeLDK3xtfNKiQ==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:M4tyX/WeQfhUnRIppRiWom7G+YJBi38Puf8YGbgLNmhfbNjc1Rg2hnzs1yr+wYCF8zyioA5zpvMn2/dV3XpESc9qS+N/Xxk7gAmpEhCJBrIRPwXSX/ZTsGTAYn4/VOHxBpkj6299UCzIG43hGsE3deHuJ8lNCsmbFwZfv+3Z3vTgHHSUZDqQIWpnhapAzMvDb1Mjcm0=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:Cn03LqhC4cMvdTONAIGibg==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:rF++aMCS1M050mG4vvCB8q2M90IMwSanzwwA4EL0Zm+0wG7zkyrkUQVaxXOHM7DUNCGAGqPdavdIyRlp9fS18D2ZAlUqAecZlwMLuHv2Bsive4Bk2ruZjvUjOQHGgY6v73mi657L5FtEc2sWJSpUSN6srYS2Wpc5Hh8IWWqiUgZK3FcBFCLIhCN8GbDKh4LyId7xpFH1guD5F8dUyXgwxwLk9bxgm+IJY8ZhJdpn+IMfPY68SsIj2yo/oukTfDWwaHCMorni/Vhm+8X42G/ny6zCg90E+pV5c18MP6Zu4RwFPfVzAFpZQmQimpYZRDkxwx2h/xhFv2tFFYI0fPhU3kJ3LoVeQfsfibITTwOOtyRgNJ/TuMfyfOrOUKvmGRq59RBEBFJ8YDwPsMagBZMZve0E9itLDpFaQu6lSXB/2WleLLTFx0JyBtcN8t+XhzccQKpi3XdcFGFSGJUkjoX5/UNSClRTmHzdPe1lUIm9HGH/hKln4Ezc3ofZ2THr3dki0LiYzxm5a7yetEruVLQc2+BE9JGXblCzThE=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:FkGIP3lZek8N+V6s46D7ZA==,type:str]
atuin_key: ENC[AES256_GCM,data:DNacPHovEkDYmBdf0bDmLNTH2abdf+epy2vdp8cL+/Y09K+O5u1ZyB7dcoUmR81dvwBEHiWDcagHg0H2zziKtQ==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:tbrrIk+1YWN9MZEuxj52nQ==,type:str]
env_credentials: ENC[AES256_GCM,data:jvUatBP3lUf4/keblKJUQZFzjWqYzw3JjHFJURe8HCp4CAWTbzC0UBueo3XikGlCJCzM/29cswV1+WEEtDnf6L8I4Q/G1QJOCCjuCFAHM1BBMWOwz98UiheIANsHN3jNcDNyFAaZfH1rJWeQWfaz201zkL6ZMG+J2N3WgDXJYZPt8YFk9yCJsGqHIunbjSrUwsZNLcvnWWHmUZUhMfjbfOtOZuFen8z4ar4p3CnDrl5ghghLXm3rNCdygKHw6v9unvviGcGEbsTSWKzzuDq61+YWKHXvA9/MhNwsawFJuP/FV3y12Svp0ck9ghZjK0rvCqohrrTpU+KnInjM7T2lGjZf3yQ1AUVt7jki4r0GdKza8m2lMdX35TyLJGThHL7JUkFgdrGsYUWOOqjNRuBx61332mB6EjoLFkhFwj4Zk2QGnSmtBEepM9Gg3I0L52T8UJArDoGM3bkcE1b4hojOF+GS/G1SDyccY/QNeOtIrTqpVKEqtYF5pNLjLlFoc/WV9SeXr1WuTctRdF2Ez/UBtG/9Ah7kUrNVmrpNy0/Xz8pEnSBe/DdV2BX9FyREbkiytQJnD+pyBI2cvIZltYzr7mX7lXx6q685JTK9CqtCPXElogT2fRwShUuJjfRG1MnY3jQmNFXeA6e088s/REb2vFE6iiLk89pfhnh0Cezg0crcXZNKylyGT5WkPQQxaa+kIM5kIsNSSN+i1kwYD/7DBJ5wUZRO8oxtrL8KCJCk2vh0zTpSXonjaVh2YLFDhoZ8/qClMigOTnOD+lz8sD4LZCMc321KWjl63u2/VkIzYd+YL7Wq/rrxHopWxV72J5mQg2811Dw0eqVWOBGVBiJZnz7C5n7fqIk8BdwYAj/notuzC76EV066HQbqjN3hMJ/hFQzMz06mOioZKSk6/ZEo3tAOduLKM7kIctcZOD1ue9R7kGcRCmjhiXw3mXRivZhm2MgA9FLYhMdxR7YFasiwYf8e,iv:NyazqBsbYoAc4PRe0HmafqYexDKV5PZ+KNRSij6fSQM=,tag:EYVsZ2o3ufLBFhjeEyJv8g==,type:str]
herdr_relay_token: ENC[AES256_GCM,data:YAx7T0ty9joFVayUZPPOcMO00JGNnmJRAV8r7SLWuhk=,iv:RJMyaQeVMBfxf9mWuYkJW/ZoIvnDxCsXguzcp+NiMXs=,tag:PB/Nr1Nrf4/knyEyBSLCMw==,type:str]
thunderbird_calendar_url: ENC[AES256_GCM,data:FOs3E3NWMNPX3t4kd32BWBdl+3Ir3Bp+sZr+/H0DLE5vJQENylxCE7MeqgxKNUqt+ccqTV7ucJZX6g5U9PD7M6h/XU9r2Waf3+q2v4RXLQUEN3lVZMVAvBHc78TG8ugmPOvW//HKpDRHiYGPaMAzHVgAyFZrApMNfWFIbIJmayv64fBLstH58S+x,iv:38mfCeTDhRKqRl7aXTqVWLNfswaXajJyQtzSUMk0nVg=,tag:rmjzcrveTqsIifpdACZkBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVnBLTkErRFNmY215bktD
            VWRDZmdIY2tJQmhCNTJHZEJvaFJsTC9nMEEwCmFMWno5cGZyeVlhbHoyOWVnWjBB
            Z0xna08xaE8zRmhDcTE1Y0w0ZkU3Q0UKLS0tIDBMb1l1QVJmWkdRNE81NUpQS2Mv
            U2xXc2o3N2JQNkZVRS91NDQwUE8wNEEKSW6Gp/92crfyqcRhcFDRzPPjt/mZIX6s
            IbCvupDlpe96ZnmuRXy17WpiQSYAavm6HFvPUu6TdgwBqe2snqdqGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdTRHVStaNWVDMEMxUmlO
            ck1lN09xTStLK1RjRG5nS1diOU9HL3lSS3dJCjVZeXozbTZaNkxKcE9PTWMyVVhT
            RWRRWTNtaE9aMHJQNmRKdmVYREZ1YVkKLS0tIHRScE5KODN0TzFPdVdtZzArdHBI
            M0xoSUZhRGVLdmtweENLL25DblBNMmsKRmH0YKItq1wHKDj8ezpMB6+ZhdazOFUk
            azp+mCvNIjeBNzC34M0VyN/+zLDpMAif24mOR65PH1kKiwE24Jxogg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ggtc2y8xmwftkdrasxvk4kschd5r7xsjv3kzhvx2k60l6mtan95q0gw0yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWTZESnNFaVZGN1RhYzB0
            VlF6Z1EyTnV1bjNHZ3RFRXFwZ2ZDTjlUbEc4CmEyeklzdnJxeitKQmpOUVYyZ2Iz
            YlEwT1FzbXVaRHFpS1kyTytmS2dBckEKLS0tIC9FVE5MTlRKK004cHZDSURRRGo2
            NmFxSFNvdzhBVzBSRUh0MTB2RkZDOGMKRyqDN/3gdz8+ZW+7AoqLq2UstbLNT7V8
            vlUOCxkODQTUWpSDRU5ggfhxDWj1G2hR4p/n8TpiZmlWqxS5cJF1eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMGE4cTB4UnY5TXdKQ2ZB
            NkhVSHcyNDd5ZjB0Nyt0eUhva3Q1OFZMMHdrCmJkQm9vcFNYa1A1bDBKM2FaSDVK
            dTc1VW5JTVo5OUcxUnJHS1VNRVc4WTAKLS0tIGIzK0o2TURVdU1LUzF1QUZQZHBV
            N29GTHQwWmFCTzh3ZEZlQlA1OUFDT2sKNEATGw6YO3SLKLF54fmRlIr4IZjA4YXC
            OQI2htEkVLoyCw8tHiC5Gxn3ViP6jVI+4S/55NJP8RQ/yW5tBRDGaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n3q6hj36mkzxntdl7zmws7l7zna8z8f930h2tj00vwc2lucszyxsdd4pzl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V2JzTUtrcnZHbTFSRTZ6
            RzVJcnhobDFsTFBrOUg1cGt3Sk5UY3RnTFVNCk9ZVmNRMUV0d0VnbzNsWktjditU
            end1czVXQ2IvUFVkK1dBWjNYOERPNU0KLS0tIEpWT2lBUG1haHRjMUgvd3BMVGZz
            MW5wMUhMcysxYi9HSkJrVUh2aXZKaVUKrVgtpbs9ADWt59PeMTN9KuV6RLDj8TS9
            j2kRAVWefJsq0F60mxP33Rl28+Xok2Thzafu4dOuLcjQ/r44JCVfxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VkhndVZWZEErQm9JbHMv
            NkhKWSsxSjd0R1B6eDhiRGxrbnN0UjlrcG1jCjBmYnh6cmlCZWMvZXRQM1lGWUJV
            eERmT3pvTEtQSlhXRG5TR1JMZ1loemcKLS0tIGZHVFlEYzdSK3htdXQweVNTWTNV
            MEIvUjZRU2lLZnpJZ21WVzVsdGdhSkUKt9BTTYOnfwoNaAF+2E3e+ayuDitDNoWT
            xZ8o2yIYozMHHRnfkCdvwhKtrtIXhbFC4RE3a0IvBrGlZzcGU7sYtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zy63ptejp3s5skj4j55ggs6vsp8gffnd367c8n3y0vzhaeyp3fms4e253u
    lastmodified: "2026-09-21T10:46:12Z"
    mac: ENC[AES256_GCM,data:CyeY+137uiEWZcF9x2K6wxj5CLLL6Apa1k301HQj3GvOuLvrleu6vAoiTT9wEJgNCzcd+HcK51ta/M5UdiTHgoC1hSZ5wvyL2Rwy8XmNAgIbusC6xazfs4qN+s9Nehil1OtcJMKaKXg7Biw1ZuZ616djPTcivEEGt8V8RqwrSDY=,iv:F09DP2N4Fi67u+hssm048GBXvxYGd7/ELmJrPTdCehw=,tag:TeVzHdfCTfUjsPgyLFbi0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
