example_key: ENC[AES256_GCM,data:FoIx/kdpuqhEJJNojGE=,iv:tL8H78oNaQibOxiEBZpvVVJs58sgtApWrBdvyAEbMXs=,tag:MG4Im9DSMgeLDK3xtfNKiQ==,type:str]
cachix_auth_token: ENC[AES256_GCM,data:M4tyX/WeQfhUnRIppRiWom7G+YJBi38Puf8YGbgLNmhfbNjc1Rg2hnzs1yr+wYCF8zyioA5zpvMn2/dV3XpESc9qS+N/Xxk7gAmpEhCJBrIRPwXSX/ZTsGTAYn4/VOHxBpkj6299UCzIG43hGsE3deHuJ8lNCsmbFwZfv+3Z3vTgHHSUZDqQIWpnhapAzMvDb1Mjcm0=,iv:Cx0g65PLG//1BRKdbotqOlT7RYRVny1iuBglrvpPGfM=,tag:Cn03LqhC4cMvdTONAIGibg==,type:str]
nz_sab_ssh_key: ENC[AES256_GCM,data:rF++aMCS1M050mG4vvCB8q2M90IMwSanzwwA4EL0Zm+0wG7zkyrkUQVaxXOHM7DUNCGAGqPdavdIyRlp9fS18D2ZAlUqAecZlwMLuHv2Bsive4Bk2ruZjvUjOQHGgY6v73mi657L5FtEc2sWJSpUSN6srYS2Wpc5Hh8IWWqiUgZK3FcBFCLIhCN8GbDKh4LyId7xpFH1guD5F8dUyXgwxwLk9bxgm+IJY8ZhJdpn+IMfPY68SsIj2yo/oukTfDWwaHCMorni/Vhm+8X42G/ny6zCg90E+pV5c18MP6Zu4RwFPfVzAFpZQmQimpYZRDkxwx2h/xhFv2tFFYI0fPhU3kJ3LoVeQfsfibITTwOOtyRgNJ/TuMfyfOrOUKvmGRq59RBEBFJ8YDwPsMagBZMZve0E9itLDpFaQu6lSXB/2WleLLTFx0JyBtcN8t+XhzccQKpi3XdcFGFSGJUkjoX5/UNSClRTmHzdPe1lUIm9HGH/hKln4Ezc3ofZ2THr3dki0LiYzxm5a7yetEruVLQc2+BE9JGXblCzThE=,iv:Ld8A1kf+K6hlOSawnjSw4yrYvKRB7X+nYh40Gmk4u9A=,tag:FkGIP3lZek8N+V6s46D7ZA==,type:str]
atuin_key: ENC[AES256_GCM,data:DNacPHovEkDYmBdf0bDmLNTH2abdf+epy2vdp8cL+/Y09K+O5u1ZyB7dcoUmR81dvwBEHiWDcagHg0H2zziKtQ==,iv:pNvTMM2U421tyjrZqAL7uPtGddeALPWhSYlI+XibtGs=,tag:tbrrIk+1YWN9MZEuxj52nQ==,type:str]
env_credentials: ENC[AES256_GCM,data:WzaSLVt3i6ZzXhGUbi4Pch6Gxn/ih6wFbPDar02KDG9SpZ+Fo5KP8+kXb0p31/Vk4YPissMCSxt4N9+0X/cD93YfXvTf/CQh7CvRXZHmzATEdidtlscp7yIm5lgCUCzD38irvBY+MA6Z6vDdPq8by1IgRlEBg4Et8dYRT2uxO1uElDLW/JthsB1ksvaQ26p/GXz95MJkShR5/XJ0z8yGiosSZ4r5go1GxsDNuGo3amMpU0fwuvpjmXXEgdvwO9XXKzu9kK8IFtmQODaSkXei4ht1/uQyb9RRfZu7an8JmzXb88bp/rFCYWfqTHwY8Qspt7N3gf9YFHzS4ZUGwjzreSQjp2VYvHwn2YE4G8c23EIa6HTbrscBcjmpyXERPjbeO20vLdKecLAiV4RdP9byWOjyAWjy4B0GS/uM/xIDsLpxuAiwTxGH2BXmihpZTt5qZ6i3Ubk1hkPwQVyUb2pooCdBUI8sZ6tGaeUSGfxL8uUWBP4eur5m5TAISb1AyIxYIKNa+tfJs2mIGtkr575h6IOatEdmPa6ML25VFNDJreeysVobGvePu81gMcZywqB4X0hqDtlYLho=,iv:xE5CAvPspz/tdvzV90JbxiNu2khlymFuILqIO3ykB6Y=,tag:si7Yabri4V+jHc6zgxulCA==,type:str]
sops:
    age:
        - recipient: age1p9ee76x0dlr7tm6v93r64p9ys5tqt9slhg6vyrn76qydh53gwuhsya0zsq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeU1mZFE0cXNOUXY5WkVS
            QlJqeUVOSWZYZTJLU0NKQjhKWFpkejVVbFhnCk1lMm41cFI4MUI5T3ZhSURzaFNa
            enNpWS91RjRDSkJoQWNNajByR2NlWEEKLS0tIEJYSCtHR3FUNVp1TC9EbDY2Slhz
            NGtVa0pPYkNIVmk5ekgxZnhaWjY1eGsKG5rRPHE0pujYsP3Uebv/EF3/mMEAmiBo
            C7rSAflz0p+bj0YVSfBaUBrvE59hiyKDNSRckHVI2C1Vn0jeQz8gtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc3FWK2xVUFA3TTBkVUNJ
            b1dFeEduUUw1ekJUUWUwOHBwaVpVU3FkVldvCjlDaUdVd0NicDl1UXhHSjBidGQw
            R1Rwa0FwOFBOQmJUcWNJb3FMTXo2VUkKLS0tIDVacXVYYTdPY2FlRlNoeTc2UTJz
            MnplNEh5bzlVcUV5SWZteENxZ2IxcU0KAsutZ4lEVvbcrRDsx7885vVqnAVQ/MID
            XQd+VtO9BFRT6BWyaEnwu+/SQfoypgtHztRZR35ZHQQWLZ3Ew/ZgXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15drpfd2kkm32g23wef9ptzyy8slrzhyk5cstwnn5pdlwtt37cqsskx2l2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMVhTWmRnSDZ0NFkrS0Zm
            SFkwMi8wTXgzVFpMeStpWHlKVG5WajdKRkFNCkNIUjV2OGlmd1VRNE5MS2NwZHpG
            NlhYSHREUHRmSFBYbW53NkhaMitNZEEKLS0tIFdrRElTcVpPYnQyK1R5UmdkVjBv
            YUZrVFRuNTlYTXB6dGNyak8zSDdMMXMK6mefAGl9dzBnW4kgwoITFyLhjTEyY3Zq
            b3uzueM64YfF90rDvhlH/KHnCoW6APace0yYtg6Dg71qPfQ4yI4C8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mv05td5h3m8wa3cqxm0npepn8jlqhrvsk9pcaewj6lmqzzew59mqwqyats
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN0F6dGtacU1TZGNFREMx
            Z2JMZmpuMEMzaVhpcjIzNFJGSFZ6Ui9mZ1hjClBtUDBXSzg4TE0yRnh6d3F6MXR0
            S1RLR3J0a2g0M3ZYRmdNSGRvUFlKdkEKLS0tIGJUdzFYYUlaNGpET04vRTBVM1NY
            dTUzLzZLK3I3cGkzY2N4M2xWMFZFU1kKxbIBu2TDi1dTAeQCb4G3+1NwnuXu59SD
            iRNuM0+ZiliaRYPwptPNLQsWoY1wJASH+3R2U8b0XRJ3XXZZf5IuQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERm4ra3lya2tYLys2QUMr
            Ti9kSlVTczgwOXY4UmkxYkFWWnpRdXQ1LzFBCjAxd1hYc0c1M2c3cmNCZVQvclM1
            MXhRUlRpMHhDZkIyTVFJWTlsb3JhcWsKLS0tIC9VYlN2c1ZHcG42T3ZaSXRidTZC
            bi92OEZDR09yNmRJWUpuNkxZSDhtK2cK4z1iQbc7WcK51lZmVCsLPgipAnu8wRpt
            P1u0/Eninuwyg/CL4WmBOG6qjal6Q7ydpL0qg9xeEhMGot+Oxmyl3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T12:48:13Z"
    mac: ENC[AES256_GCM,data:5mcs9cbmB7WNn0sGNM4yQ++Vm3VGQeDrsswODfzKcu23PgBOT+TL9lkflkCjoB5gQABUnsHXIm2ZN3K6LhhBjwzNpVWbSPAH4Q/nXukWzLLzzUIaQqpXFiUoC9OEEK5akRd1la23LssY3xjdJmwcTfw6yKju7bN/diXlLaDXuo0=,iv:l5fY3XWYgNZf7uq0IZpVaLp083eGvwtTn3EzHQ+CcLI=,tag:Os5pl2M0myq2LWjjvTn6aw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
