nix-cache-priv-key: ENC[AES256_GCM,data:j34ZB4xHhtjnUH1XbLr0Z9XJp314oSSi5dSEkTfDUfbMDOXEEzDB4ytzY+HVUkVLapvTydJ/ChwF61GGe08onNFxYkATl6F5GBDebCpVQar9b7Dd4Av8GJtM7MhqRQPmjUYywnkrZj8=,iv:kR0p0tCdOzKuiyuXca82wijl0gokMeX5H/R0cZi1hIE=,tag:jKTqvmjcl3ucXQp8iP8A+A==,type:str]
sops:
    age:
        - recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvenF0NmJydjlaMUtoYjNO
            eTJPTDI0bVo2OWYyQVFnWitNcC9RakJwSUZRCnNnNDJaS0V0dmhwcDVCS0VCdjdF
            Z25hamdjUXJ5WHo5R0gzd256dzl2OGcKLS0tIGVqU0hkU1hVZ3R1cHdwVG12Sk5W
            ZXYreFpWYVp5VWYzcHlEZHdmem14aVkKPY4DyaJb/Moa8JVZgdZxR/eDOiZYqFH0
            MFozvewePfV6f2Ygvj0QcSkzEH5p81c3wXgRkig2F3PVPjWHRbH8FQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfq3wfu4086pwxusqca92wh3p7hzr7gn3suqnyfqy4vqg30k3cyqft4pcf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYnkwcjZGcHJMa3JFZWk1
            aXdEcHhJNi9HRDRGUmM3dHdmS3A4eEg5VHlRCldtMFd2VFIxNTJzYVkwQWdTTnVy
            TGtRek9mMTJYZkREYUNxRDAxakgwTzAKLS0tIGdSL2lVNlV2alpseUtiUXZESHQr
            bHdNeW5ISWZjT1cyTWU2RU95NVc5cFkKKLy5xxNzM+VsZZf8j0OLEZCO1cAWsVZh
            AcoJkMIZOVvPKA4brSx8xsn3g7upbJ9Pu4RGTywK8nBer8U+FVoC3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t69sgcam6f6h6xl06qf3zt8hc6zhx5vfy32e3ggvu4hylldgv4nq0w40rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreWhGRFF3V2FpcUJ5Q3cr
            L2J1bVpDOUVTVHhhdTFiVzlMNEgxbVVFZURNClBkeE5qZ2dRL3dFR3lHWE9MWnRX
            K1JpV1JZbCsyaWUzREtVWnZPbDJDaW8KLS0tIDVUcTU1bWJDenJvVHk0U3JXZGsw
            VlExWldJeFRrZGNicGJIWEt1OEVudFUKoCRY57U1t2uw7ay8aL1vKucrCgQqljJw
            7E8T2QJdJYQgcHKxQ9lylboKyEmnMSeDXaEoxRqMA/rfTtCBQT3TXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T08:59:26Z"
    mac: ENC[AES256_GCM,data:lGMeJNv2bx9lFPCIP7jCELLeMKsHDmeEU8oXqamD9ia/BcOMXzaAHGifjeZy0KDthuUlP3udAqfCFBz6tq3MAk2j6niIVHy3GOa6NymwSqSY2Ts519uMhRpoPmHSVLUCRVBCTg4+M0HJMM5AL7cr3DWCtS/jWA7/xAEu0eQvDWI=,iv:X9Kb43L5WdApnQdYRxDbhnpfenS4WRsGRkw+f//gltI=,tag:zBf0XIYakIKq4w8Qgi+oAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
