# NixOS Cache Builder secrets for beez
# 
# To set up:
# 1. Generate cache signing keys:
#    sudo nix-store --generate-binary-cache-key beez.sbulav.ru \
#      /tmp/cache-priv-key.pem /tmp/cache-pub-key.pem
#
# 2. Edit this file with sops:
#    sops secrets/beez/default.yaml
#
# 3. Add the private key content below (uncomment and paste):
# nix-cache-priv-key: |
#   beez.sbulav.ru-1:base64encodedprivatekey...
#
# 4. Save the public key for distribution to client machines:
#    cat /tmp/cache-pub-key.pem
#    Example: beez.sbulav.ru-1:base64encodedpublickey...
#
# 5. Add public key to client configurations (nz, zanoza, mz):
#    system.nix.cache-servers = [{
#      url = "http://beez.sbulav.ru:5000";
#      key = "beez.sbulav.ru-1:...";
#    }];

# Placeholder - replace with actual encrypted key using sops
# nix-cache-priv-key: REPLACE_WITH_ENCRYPTED_KEY

sops:
  age:
    - recipient: age1pd5lj9knvy94466f0np5fww60efnqmw6nkgca776rff6wx9x334qp2neh6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        PLACEHOLDER_ENCRYPTED_AGE_KEY
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        PLACEHOLDER_ENCRYPTED_AGE_KEY
        -----END AGE ENCRYPTED FILE-----
  unencrypted_suffix: _unencrypted
  version: 3.10.2
