nix-cache-priv-key: ENC[AES256_GCM,data:v7j7BuuVBPd6LNG7mkl5Q7JLJaQmSXLZ5b64+SBtq1MFq6+/9A0WDTD6rUH0gyLAzAfEwC/xNgNJ6MFd89A9zHBEBtY7HmXNV+dFYsM2JetX5YgXG5e44khfEx24TXBSR6aUYV2beLk=,iv:kR0p0tCdOzKuiyuXca82wijl0gokMeX5H/R0cZi1hIE=,tag:gzVvioNM/3Ljvx4pZzx8Aw==,type:str]
sops:
    age:
        - recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRFZRQnBNRllVVVJlQXZG
            WkF3VmppbG5qNjlxRlhlSEQrYzB5QlFHV0IwCk14cTgwYlJTRC9RWlkwZnUrbkl0
            Z09CYStMZjRGYlh1WnNzbW9EM0lCOVkKLS0tIHArNytqaTZmdElnc01NNmZHS25S
            QktDS1F6bEdxbmlmS1lwUFptNzZwMVUKPorK6owSo/BI9dyqpq0r2u/Tal8feYzS
            ZJhmbbf3HtnB4Lm4R7en7cv3CULIf4oS2omLdzyboLd9fm+azACcTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfq3wfu4086pwxusqca92wh3p7hzr7gn3suqnyfqy4vqg30k3cyqft4pcf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZU5hc1g1RWIzdkF0NFJL
            QUtHZU9EaURpcGxiL1VXNG80NnMzR3dRQWxrCmFSNE9JdHY0eFBIUGdDTUhjZzlI
            cG1rcVZKQkZJbFBIK1MxcjkyQXhWQzAKLS0tIEdnVkF4bWl4VllOclVtVGpPekxt
            Q1FHMkJpdStsaHVHRTg3SUpCOEJrSTgKzrNXk6OlRC4Mo0VhtBnx+TPapzkMiPPG
            nhd876CeP2l148TQcW1A8AjkmQsJQG8Y42pk1tWKp+eSXHuTZhD3dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T07:46:33Z"
    mac: ENC[AES256_GCM,data:/wPr7z1EzTN+mYAioqaVJ5pMl3YkSOpHQGtSJkIowLbNKSlNRWzXdJg9wUH84XRJLCItRWy1fYhXf8IQ0dqT+l8g8jSr5z7KLSGh1NVX0BzlKuGAODhL32WxASXhtqRu/6PSN0XrlRFCnUjdO1u9aAisix8F5vST6a6jPFUCNDc=,iv:8zfLXN8bGPSXvk8OnwM29Cw7c224UQ5YqDbg64+aY/Y=,tag:rhixXr9F4bwZa+8B0tSG8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
