nix-cache-priv-key: ENC[AES256_GCM,data:SIy3Ooap7VUGdwk7P9zodrzm3rLdqHY2du5nkKAk7KbfYeuwEHUItE/F2AaD4Jc4QGtyet7TH0LeUCF1rseEJCqITJim5TPBUujmjNFOSG3htFa9QEbqopgLOrtqs/bynB7X62e1WFo=,iv:wLLOA9Bt+tkRNNh/6Z7fuVQF6AL4W0FemU//G9hGcxw=,tag:acsvcNALyjaDE/0ig6HeJA==,type:str]
sops:
    age:
        - recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvenF0NmJydjlaMUtoYjNO
            eTJPTDI0bVo2OWYyQVFnWitNcC9RakJwSUZRCnNnNDJaS0V0dmhwcDVCS0VCdjdF
            Z25hamdjUXJ5WHo5R0gzd256dzl2OGcKLS0tIGVqU0hkU1hVZ3R1cHdwVG12Sk5W
            ZXYreFpWYVp5VWYzcHlEZHdmem14aVkKPY4DyaJb/Moa8JVZgdZxR/eDOiZYqFH0
            MFozvewePfV6f2Ygvj0QcSkzEH5p81c3wXgRkig2F3PVPjWHRbH8FQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xfq3wfu4086pwxusqca92wh3p7hzr7gn3suqnyfqy4vqg30k3cyqft4pcf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYnkwcjZGcHJMa3JFZWk1
            aXdEcHhJNi9HRDRGUmM3dHdmS3A4eEg5VHlRCldtMFd2VFIxNTJzYVkwQWdTTnVy
            TGtRek9mMTJYZkREYUNxRDAxakgwTzAKLS0tIGdSL2lVNlV2alpseUtiUXZESHQr
            bHdNeW5ISWZjT1cyTWU2RU95NVc5cFkKKLy5xxNzM+VsZZf8j0OLEZCO1cAWsVZh
            AcoJkMIZOVvPKA4brSx8xsn3g7upbJ9Pu4RGTywK8nBer8U+FVoC3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t69sgcam6f6h6xl06qf3zt8hc6zhx5vfy32e3ggvu4hylldgv4nq0w40rt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreWhGRFF3V2FpcUJ5Q3cr
            L2J1bVpDOUVTVHhhdTFiVzlMNEgxbVVFZURNClBkeE5qZ2dRL3dFR3lHWE9MWnRX
            K1JpV1JZbCsyaWUzREtVWnZPbDJDaW8KLS0tIDVUcTU1bWJDenJvVHk0U3JXZGsw
            VlExWldJeFRrZGNicGJIWEt1OEVudFUKoCRY57U1t2uw7ay8aL1vKucrCgQqljJw
            7E8T2QJdJYQgcHKxQ9lylboKyEmnMSeDXaEoxRqMA/rfTtCBQT3TXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T09:59:30Z"
    mac: ENC[AES256_GCM,data:OWLWJuAOdz9pe6iGweg6j0ujsxBhMf33o5k4iIxQ171C4zHWAkpvsExRFxnmqy/+cZNlvWgU7YlJzcgPIO6u158F0hvA5Qwuc2HbPlUKJ6gTMGpI5eg/KyP4cD0RVvIF46WPm0Z26q4EvIJGy0ybD52zHjYstpSpMbaOhzr8Cvc=,iv:AcU5CjMEvL96vLasUuRYmduXZJTSvc2Xg09lktiEJMM=,tag:KvAC2n8XW4RgYOaHvjlvCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
