nix-cache-priv-key: ENC[AES256_GCM,data:SIy3Ooap7VUGdwk7P9zodrzm3rLdqHY2du5nkKAk7KbfYeuwEHUItE/F2AaD4Jc4QGtyet7TH0LeUCF1rseEJCqITJim5TPBUujmjNFOSG3htFa9QEbqopgLOrtqs/bynB7X62e1WFo=,iv:wLLOA9Bt+tkRNNh/6Z7fuVQF6AL4W0FemU//G9hGcxw=,tag:acsvcNALyjaDE/0ig6HeJA==,type:str]
telegram-notifications-bot-token: ENC[AES256_GCM,data:e6JfpXE10QbOnLs88Ck9kkUNQD2w30INlaDjfNtv/K4oGYnsDRRi5sJ7D86MxHY0nBjYe4OpfdFMtr6ohFw=,iv:BbE2vWmdYkM+boJzHsSSKq98qSl7prH8gcNyQzttOqk=,tag:INl92UHvsaKyeySNezJ8yA==,type:str]
shared:
    email-password: ENC[AES256_GCM,data:CTql5ffU24i++i59v87UkQ==,iv:VHtRiMKG31lvIvr/i1uedW7SIAF7Ro+A5zjwxVQwqrM=,tag:IFd+S6TcVVgtoGUDaCJdXg==,type:str]
nix-remote-builder-ssh-key: ENC[AES256_GCM,data:5GWhDPNCt08iOGsFr4VFL6TPgeyVNPqckUgoKZnF877pXHNf/z5MbMJ9dYioN4mFNrN2WOvXLJj7rQSbRng8sWoxkNLtwI4M1HT244xiD3mGmCidhxp50NUHG98k/niZhRinz7RVrlC5rCCcJhcLb4QX5ZeIWi3dnERRVCeXpPYHpq1MFBOcuxriWct7QCd8fMRIExeaqk1i5CRrOvsKCW7YrdhUmXgyrrK3g154RMhHRKsNWvt1bcADpfnCqEe64RU8bmBn9DXqsyMI/fs7jkF6gljllvAL1AqY5xUzfSPJaJ6UPYmC5UcuNTkUpfpZ5z7Eaj9eQcldX9FgwO2Dme3MWrLme0oyqIu5hIN41K3kwRWOgR/sIDlg54u54evUl504jxERyBBMoJm1Ehw1r7vMwbZ5t9lss8LhI/htaIJWJdi9j+MLci6MnsdvJ7jbRKt9FjTCkcHlS+3bkfxH4bCGRp4pBJA4c+c52V5XITVLGMB2kY0MTiJewt4SrS2tCglrytxzFX5pZJeCe+sYrXvYcCinFdkUfdaf5ZHdleC8/RQ=,iv:G4PYpEDyk1HshbVUUw+3TAGysdx/mePHpDGAUIA47vw=,tag:DLefcJ8r0YTDA4OLN4yR2g==,type:str]
backups:
    restic_odroid: ENC[AES256_GCM,data:c85qZIDGcmgyjw==,iv:kajyMujF0Ip4E8Yg2EylLPaAekXi/JxY6PBQHNf+N4I=,tag:4cyS4tSW+zJMEaunrvdiAg==,type:str]
traefik-cf-env: ENC[AES256_GCM,data:jXCByryCkShX6iLWOMWOepmOS1rBDm2ruN+gCVfinn60XuRRX5+nTMQs5A0t3LpXgihxPtrxSuoSC8a4s8TtsmzFL9lj3K+SUCX822uLj/HQnuRbIahs0Q==,iv:AAjA93NXHTQ3jwydOTrirbeRiX5/s8buuaZmws/w51w=,tag:KhJyHzxYGyiynk4MtDGrFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcHFlWmpsRm1LQmZmTXE0
            VzFBUENVMnRwRzhsdlpPM1NJY25PQUoyY0VnCkM1Mng1YitTcks5VmM5VGtvemhw
            YUFrcjdDNzR5MWphTElHSzI5KytkWkkKLS0tIGoyR3NjeUdwMURHNjBBSkt1dnhJ
            eC9CM3B6YktsVUFLUW1hSEo1NXlmMUEKP6SQFsnYgLBgJFdy+0vzM4CCRymEIiWv
            XchZxSCnzOLTt+HNkvkvZLZZHncBN3hFFKPoSHZwjMdmu16wXGg12A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7es34nulexklu4qjywqy3hqycn3qfjmhlj7usurx7ehruvaddysqsc8gm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQWhwNXBpWndzczRUTWRl
            Z0pvZ3llTkNySUMzY1VzdXRyY1ZjdkcxNDNNClh4dENtUlJLK0h2RU8vN3VLSjJU
            Wm9laDNYQ2RSRysyTG1ZL2xPKzlzakkKLS0tIGIwSlZhUDdzMmdVSEszM0hwdmx4
            OUNKNEZYWW53dDlXaVluMVg2UTViUmMKCua25ER0OiJIbmwYG/RII016r53gdA0n
            nIdHStZw8UhBSU4WyKH/65uoGTBGO9ZQjHM6+3UKtWP0DaxThICP9w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t69sgcam6f6h6xl06qf3zt8hc6zhx5vfy32e3ggvu4hylldgv4nq0w40rt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYWtUUHkwdlg2Y3NuaUlV
            RnVpbVJQYkJCeUZPUUt3SkhOQ0tKbW14UFNrCjFaVngyUW5jZUJqWExHQUhSSUdG
            TjA2dzNGTzJnZTdkTHdRZnJQZWl0cGMKLS0tIDRnYnVVMGVqbjJSUzdoWlVqdFN1
            c1QyVUZkR2dxQklVZjFGYTRqZ2x5SXMKc++Fp52Jky+4bEmyBDOFouLoH6AwHVfv
            OgALxmXdJl1izIsni3PKi1DHiLZwxtZNS1JhYlZxfZcXn88N0+1CNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rax0jv4pj2yuegt7e5ea2wzu486mz9nl3vhsa09y45lzw8cj58stfdd6d
    lastmodified: "2026-09-26T11:22:42Z"
    mac: ENC[AES256_GCM,data:iIJXKfZ5v/LYa6cWz59KslC21x07rB/iKh8cAZbtM/CltAQn/0zvTuQqQlfL6/EZh4KzDqbLvtSiQ82FAmCYoncRGs+60WvLrUk1YQAeODEAAPtdb2cSHwTAwXD/ZZnOYcMvGPoKnMec2MZ3haEXHd7Yn54mY3Gp1wDqMZtMkh4=,iv:r44Yi3YuHe4/AKwe1W3yWoEJtN5XL8OkTl9gw0/ALdE=,tag:LsTRFxX/zPu4tBQPDxG05A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
