{
 "title": "UPS info via NUT prometheus exporter",
 "tags": [
  "ups",
  "nut"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(network_ups_tools_device_info{job=\"nut\"}, host)"
    }
   },
   {
    "name": "ups",
    "label": "UPS",
    "query": {
     "query": "label_values(network_ups_tools_device_info{job=\"nut\", host=~\"$host\"}, ups)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Battery Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{job=\"nut\", host=~\"$host\", ups=~\"$ups\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{job=\"nut\", host=~\"$host\", ups=~\"$ups\"}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{job=\"nut\", host=~\"$host\", ups=~\"$ups\"}"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{job=\"nut\", host=~\"$host\", ups=~\"$ups\"} == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{job=\"nut\", host=~\"$host\", ups=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups}}"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{job=\"nut\", host=~\"$host\", ups=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups}}"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{job=\"nut\", host=~\"$host\", ups=~\"$ups\", flag=~\"OL|OB|LB\"}",
     "legendFormat": "{{host}} {{ups}} {{flag}}"
    }
   ]
  }
 ]
}