# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9558676c-b2b9-4c4f-9e5e-298d285ab20a";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1DB5-C455";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/c4b2cd1f-14c4-4c07-bb28-c97d149bbe9f";}
  ];

  # Ensure the mountpoint exists at boot
  systemd.tmpfiles.rules = [
    "d /mnt/ext 0755 sab sab -"
    "d /tank 0755 sab sab -"
  ];

  # fileSystems."/mnt/ext" = {
  #   device = "/dev/disk/by-uuid/B62873392872F7A7";
  #   fsType = "ntfs-3g";
  #   # Automount means: don’t block boot; mount on first access
  #   options = [
  #     "x-systemd.automount"
  #     "nofail"
  #     "x-systemd.idle-timeout=60s"
  #     # optional ownership/permissions if you want user-writable:
  #     "uid=1000"
  #     "gid=100"
  #     "umask=022"
  #   ];
  # };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
