# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/67988e1d-851b-498d-8af1-bacd7e6f4b74";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7217-68A8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/faaffaaf-1b1a-42d9-b01d-c0cbd0735f17"; }
  ];

  # Ensure the mountpoint exists at boot
  systemd.tmpfiles.rules = [
    "d /mnt/ext 0755 sab sab -"
    "d /tank 0755 sab sab -"
  ];

  # fileSystems."/mnt/ext" = {
  #   device = "/dev/disk/by-uuid/B62873392872F7A7";
  #   fsType = "ntfs-3g";
  #   # Automount means: don’t block boot; mount on first access
  #   options = [
  #     "x-systemd.automount"
  #     "nofail"
  #     "x-systemd.idle-timeout=60s"
  #     # optional ownership/permissions if you want user-writable:
  #     "uid=1000"
  #     "gid=100"
  #     "umask=022"
  #   ];
  # };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
