# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5907e44e-a9da-4b85-b6b6-750810d635fc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/77F0-7FF9";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking = {
    useDHCP = lib.mkDefault true;
    hosts = {
      # To make local resources work under VPN
      "192.168.89.207" = [
        "zanoza"
        "zanoza.sbulav.ru"
        "jellyfin.sbulav.ru"
        "authelia.sbulav.ru"
        "home.sbulav.ru"
        "nextcloud.sbulav.ru"
        "traefik.sbulav.ru"
        "flood.sbulav.ru"
        "grafana.sbulav.ru"
      ];
      "192.168.92.194" = [
        "beez"
        "beez.sbulav.ru"
      ];
    };
    # interfaces.wlp3s0.ipv4.routes = [
    #   {
    #     address = "192.168.89.0";
    #     prefixLength = 24;
    #     via = "192.168.88.1";
    #   }
    # ];
    search = [ "sbulav.ru" ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
