name: Check flake inputs
on: [push, pull_request, workflow_dispatch]
jobs:
  checks:
    name: Check expressions on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64-linux, aarch64-darwin]

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v16
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: ${{ env.CACHIX_BINARY_CACHE }}
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
